export const factoryAbi = [
  {
    inputs: [
      { internalType: "uint256", name: "totalSupply", type: "uint256" },
      { internalType: "uint256", name: "remainingTokens", type: "uint256" },
      { internalType: "uint256", name: "accumulatedPOL", type: "uint256" },
      { internalType: "uint256", name: "marketCapMin", type: "uint256" },
      { internalType: "uint256", name: "marketCapMax", type: "uint256" },
      {
        internalType: "uint256",
        name: "tokensNeededToMigrate",
        type: "uint256",
      },
      { internalType: "uint256", name: "poolCreationFee", type: "uint256" },
      { internalType: "uint256", name: "migrationFee", type: "uint256" },
      { internalType: "uint256", name: "feeBPS", type: "uint256" },
      { internalType: "uint256", name: "uniFeeBPS", type: "uint256" },
      { internalType: "address", name: "feeCollector", type: "address" },
      { internalType: "address", name: "uniFeeCollector", type: "address" },
      { internalType: "address", name: "signer", type: "address" },
      { internalType: "address", name: "uniswapV2Router", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "CannotMigrateYet", type: "error" },
  { inputs: [], name: "FeeBPSCheckFailed", type: "error" },
  { inputs: [], name: "FeeCollectorIsZero", type: "error" },
  { inputs: [], name: "InvalidSignature", type: "error" },
  { inputs: [], name: "MarketCapMaxIsZero", type: "error" },
  { inputs: [], name: "MarketCapMinGreaterThanMax", type: "error" },
  { inputs: [], name: "MarketCapMinIsZero", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "POLTransferFailed", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "RemainingPOLIsZero", type: "error" },
  { inputs: [], name: "RemaningTokensIsZero", type: "error" },
  { inputs: [], name: "ReusedSignature", type: "error" },
  { inputs: [], name: "SignerIsZero", type: "error" },
  { inputs: [], name: "TokensNeededToMigrateIsZero", type: "error" },
  { inputs: [], name: "TotalSupplyIsZero", type: "error" },
  { inputs: [], name: "UniFeeBPSCheckFailed", type: "error" },
  { inputs: [], name: "UniFeeCollectorIsZero", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokensOutstanding",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "POLAmount",
        type: "uint256",
      },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "uniFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "progress",
        type: "uint256",
      },
    ],
    name: "BuyGivenIn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokensOutstanding",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "POLAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "refund",
        type: "uint256",
      },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "uniFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "progress",
        type: "uint256",
      },
    ],
    name: "BuyGivenOut",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "CanMigrate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "CreateHydrapadPresaleToken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "POLAmount",
        type: "uint256",
      },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "uniFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "progress",
        type: "uint256",
      },
    ],
    name: "CreateHydrapadPresaleTokenAndBuy",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      { indexed: true, internalType: "address", name: "pair", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokensToMigrate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokensToBurn",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "POLToMigrate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "migrationFee",
        type: "uint256",
      },
    ],
    name: "Migrated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokensOutstanding",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "POLAmount",
        type: "uint256",
      },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "uniFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "progress",
        type: "uint256",
      },
    ],
    name: "SellGivenIn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokensOutstanding",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "POLAmount",
        type: "uint256",
      },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "uniFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "progress",
        type: "uint256",
      },
    ],
    name: "SellGivenOut",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "remainingTokens",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "accumulatedPOL",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "marketCapMin",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "marketCapMax",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokensNeededToMigrate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "poolCreationFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "migrationFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeBPS",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "uniFeeBPS",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "feeCollector",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "uniFeeCollector",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "signer",
        type: "address",
      },
    ],
    name: "SetParameters",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "amountOutMin", type: "uint256" },
    ],
    name: "buyGivenIn",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "tokenAmount", type: "uint256" },
      { internalType: "uint256", name: "maxPOLAmount", type: "uint256" },
    ],
    name: "buyGivenOut",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "uint256", name: "nonce", type: "uint256" },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "createHydrapadPresaleToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
      { internalType: "uint256", name: "nonce", type: "uint256" },
      { internalType: "uint256", name: "tokenAmountMin", type: "uint256" },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "createHydrapadPresaleTokenAndBuy",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAccumulatedPOL",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "getCanMigrate",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getFeeBPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getFeeCollector",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getHydrapadPresaleTokens",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMarketCapMax",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMarketCapMin",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMaxFeeBPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getMaxUniFeeBPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getMigrationFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPoolCreationFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRemainingTokens",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSigner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokensNeededToMigrate",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalSupply",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getUniFeeBPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getUniFeeCollector",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getUniswapV2Router",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "signature", type: "bytes32" }],
    name: "getUsedSignatures",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "tokenAmount", type: "uint256" },
      { internalType: "uint256", name: "amountPOLMin", type: "uint256" },
    ],
    name: "sellGivenIn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "tokenAmountMax", type: "uint256" },
      { internalType: "uint256", name: "amountPOL", type: "uint256" },
    ],
    name: "sellGivenOut",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "totalSupply", type: "uint256" },
      { internalType: "uint256", name: "remainingTokens", type: "uint256" },
      { internalType: "uint256", name: "accumulatedPOL", type: "uint256" },
      { internalType: "uint256", name: "marketCapMin", type: "uint256" },
      { internalType: "uint256", name: "marketCapMax", type: "uint256" },
      {
        internalType: "uint256",
        name: "tokensNeededToMigrate",
        type: "uint256",
      },
      { internalType: "uint256", name: "poolCreationFee", type: "uint256" },
      { internalType: "uint256", name: "migrationFee", type: "uint256" },
      { internalType: "uint256", name: "feeBPS", type: "uint256" },
      { internalType: "uint256", name: "uniFeeBPS", type: "uint256" },
      { internalType: "address", name: "feeCollector", type: "address" },
      { internalType: "address", name: "uniFeeCollector", type: "address" },
      { internalType: "address", name: "signer", type: "address" },
    ],
    name: "setParameters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
];
